# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2018-08-18 03:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20180818_0102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='files',
            field=models.ManyToManyField(blank=True, to='blog.Attachment'),
        ),
        migrations.AlterField(
            model_name='post',
            name='images',
            field=models.ManyToManyField(blank=True, to='blog.ImageAttachment'),
        ),
        migrations.AlterField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(blank=True, to='blog.Tag'),
        ),
    ]
